### ISSUE TITLE
Reproducible specifications

### ISSUE THREAD

**Issue by jamesdiacono** [douglascrockford/JSCheck#34]
I recently made a change to my copy of JSCheck, and wanted to report back because I think it's been a success.

I use JSCheck's specifiers extensively outside of property-based testing, to generate random data for UI demos and simulations. One problem I've had is that there is no way to control the randomness of specifiers, meaning that a demo or simulation can not be reproduced. This is sometimes useful when debugging edge cases, or to demonstrate a particular scenario.

I observed that a specifier is a kind of generator and generators are allowed to take arguments, as is clear from the generator factories exhibited in How JavaScript Works:

    function limit(generator, count = 1) {
        return function (...args) {
            if (count >= 1) {
                count -= 1;
                return generator(...args);
            }
        };
    }

What I did was modify the signature of specifier functions. Instead of ignoring their arguments, they can take an optional `random` function. When a specifier receives a `random` function, it uses it in place of `Math.random` and passes it down to any specifiers it calls:

    function boolean(bias = 0.5) {
        return function (random = Math.random) {
            return random() < bias;
        };
    }

    function inside(bbox) {
        const longitude_specifier = jsc.number(bbox[0], bbox[2]);
        const latitude_specifier = jsc.number(bbox[1], bbox[3]);
        return function (random) {
            return [
                longitude_specifier(random),
                latitude_specifier(random)
            ];
        };
    }

This makes it possible to pass in a pseudo-random number generator (PRNG) to override the default randomness. Then a test, demo, or simulation can be reliably reproduced:

    const my_seeded_random = prng(42);
    const specifier = jsc.number();
    const data = specifier(my_seeded_random); // predictable output!

Modifying `claim` and `check` to support reproducibility was straightforward:

    jsc.claim(
        "inverse",
        function predicate(verdict, a) {
            return verdict(halve(double(a)) === a);
        },
        [jsc.number()]
    );
    jsc.check({
        random: my_seeded_random,
        on_report: console.log
    });

Changing the the specifier signature in this way is almost completely backwards compatible, but I should mention some situations where breakage can occur. In practice I was only bitten in once, where I was relying on a specifier ignoring its arguments:

    const result = string.replace(/-/g, specifier);

The only other breakage, purely theoretical, arises from the necessary removal of a JSCheck feature I never use. It turns out that JSCheck allows specifiers as bounds parameters, but the usefulness of such freedom is questionable at best:

    const weird_specifier = jsc.integer(
        jsc.integer(0, 5),
        jsc.integer(10, 15)
    );

(This feature is incompatible with my scheme because the `random` capability is not available to factories, only specifiers.)

I realize that I have made quite a fundamental change to my JSCheck, so I am not expecting it to be adopted lightly. But I am convinced that specifiers are more useful when they are reproducible.

**Comment by douglascrockford** [comment]
I really like this. In general, I consider 'random' to be a capability that should not be generally available in the ambient environment. Passing it in is the right thing to do. 

But I do not want to make a breaking change, since the bounds generators are in the book. It may be more important as an example of higher level composition than as a testing specification feature, so I want to maintain compatibility with the book.

**Comment by douglascrockford** [comment]
Another way would be to add jsc_constructor.set_random(). It's use is optional. If you do not call it, Math.random is used. If you call it, you can pass in your own random function that will be used instead. Does that give you enough of what you want?

**Comment by jamesdiacono** [comment]
I don't think so. I have specifier factories that are not built on top of JSCheck's specifiers, so changing JSCheck is not enough. The specifier pattern itself must be changed, for composability. I really don't mind maintaining my own fork, I just wanted to share an interesting observation.
